# Numpy tutorials
Numpy is a general purpose array-processing package.
It provides a high performance multidimensional array object,and tools for working with these arrays.
It is the fundamental package for scientific computing with Python

# What is an Array?
An array is data structure that stores values of same data type.In Python,this is the main difference between arrays and lists.While python lists can contain values corresponding to different data type,arrays in python can contain only values corresponding to same data type

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.shape  #it tells number of rows and columns present in array and for one dimensional array it return no of elements present

(5,)

In [6]:
# Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [9]:
arr.shape


(3, 5)

In [10]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [11]:
arr.shape



(3, 5)

# Indexing

In [12]:
# Acessing the array element
arr=np.array([1,2,3,4,5,6,7,8,9])


In [13]:
arr[3]

np.int64(4)

In [14]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr=np.array([[1,2,3,4,5],
              [2,3,4,5,6],
              [9,7,6,8,9]])

In [17]:
arr[0:2,0:2] #indexing in multidimensional array

array([[1, 2],
       [2, 3]])

In [21]:
arr=np.arange(0,10)  #this function creates one dimensional array which contain value in range 0 to 9

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [25]:
arr1=arr
arr1[1:]=100

In [26]:
arr1

array([  0, 100, 100, 100, 100])

In [27]:
arr

array([  0, 100, 100, 100, 100])

we say that when we copied array arr to array arr1 then changes made to arr1 reflect to arr also to prevent this we should use copy function

In [29]:
arr1=arr.copy()

arr1

array([  0, 100, 100, 100, 100])

In [30]:
arr

array([  0, 100, 100, 100, 100])

In [31]:
arr1[1:]=1000
arr1

array([   0, 1000, 1000, 1000, 1000])

In [32]:
arr

array([  0, 100, 100, 100, 100])

In [33]:
### some conditions very useful in exploratory Data Analysis
val=2
arr<2


array([ True, False, False, False, False])

In [34]:
arr*2

array([  0, 200, 200, 200, 200])